import java.io.IOException;
import java.util.HashMap;

public class CGIHeader extends HTTPHeader{
	
	// Code for parsing headers generated by CGI script
	// Inherits from HTTPHeader as only the parsing code is different
	CGIHeader(String header) throws IOException{
			
		attributes = new HashMap<String, String>(); // Hash map of header attributes
		String [] headerLines = header.split("\r?\n"); // split on \r, \r\n or \n
		for(int i = 1; i < headerLines.length; ++i){
			
			// Put all headers in the hashmap
			String []tokns = headerLines[i].split(":"); // split each header line at :
			if(tokns.length != 2) continue; // Weird header line
			attributes.put(tokns[0].trim().toLowerCase(), tokns[1].trim()); // Insert into hashmap
		}
		
	}

}
